# Estágio 1: Build
FROM maven:3.9.9 AS build

WORKDIR /app
COPY . .
RUN mvn clean install -DskipTests  # Aqui estamos apenas instalando as dependências e gerando o artefato, sem rodar os testes

# Estágio 2: Testes
FROM maven:3.9.9 AS test

WORKDIR /app
COPY . .

# Rodar os testes no estágio de build (usando o Maven)
RUN mvn test  # Rodando os testes aqui

# Estágio 3: Imagem final
FROM container-registry.oracle.com/graalvm/jdk:21

WORKDIR /app
COPY --from=build /app/target/backend-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
