# Estágio 1: Build
FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
# Faz o build e pular testes (essencial pois não tem banco de dados na hora do build)
RUN mvn clean package -DskipTests

# Estágio 2: Imagem Final Otimizada
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

# Copia o JAR gerado no estágio anterior
# O asterisco *.jar pega qualquer nome, evita erros se a versão mudar
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

# --- PARA RODAR NO PLANO FREE ---
# -Xmx350m: Faz o java usar no máximo 350MB de RAM. 
#           Isso deixa ~160MB livres para o Sistema Operacional do container respirar.
# -Xss512k: Reduz o tamanho da pilha de threads (economiza memória).
ENTRYPOINT ["java", "-Xmx350m", "-Xss512k", "-jar", "app.jar"]